### ISSUE TITLE
Shipping method don't recognize free shipping coupon

### ISSUE THREAD

**Issue by ArtisSk** [mijora/omniva-woocommerce#103]
Hello.

I've encountered a weird bug. I have made a coupon with free shipping option. So whenever someone uses this coupon, he should get free shipping despite the fact if he is qualified for free shipping by order total (I have selected that all orders over 20Euro will get free delivery). Now, when I enter this coupon, i get free shipping in other delivery methods, but not in Omniva. It still shows me shipping fee, where as shipping method (DPD) works as intented and removes shipping cost. Now i'm wondering if this is a bug in Omniva shipping plugin or am I doing something wrong here.

Any directions will be appreciated.

Thank you!

**Comment by markakk** [comment]
Hello,

The Omniva plugin has its own separate free shipping system, so regular Woocommerce free shipping for Omniva delivery methods does not work.
If you want to use the free shipping coupon with Omniva, you need to select the coupon under "Free with coupon" option in the Omniva settings.
![paveikslas](https://user-images.githubusercontent.com/71830881/173505916-87373999-0d33-4eab-abed-638e83f25df6.png)

**Comment by ArtisSk** [comment]
Hello,

thank you very much for the explanation. But i was wondering if these free coupon codes are auto generated, or I can add my own code somewhere in Omniva plugin settings? Because in your screenshot I see coupon code 'FreeAllShipping', but I have lots of codes like 000y6js1 ( random strings ) available in dropdown. 

Thank you!
