### ISSUE TITLE
Free delivery coupons does not work

### ISSUE THREAD

**Issue by jamajamajaaama** [mijora/omniva-woocommerce#116]
I saw in changelog, that the issue has been solved, but still, if I create a new coupon with free delivery for particular product, the discount does not work with Omniva - delivery price is still calculated.

**Comment by markakk** [comment]
Hello,

To use free delivery coupon for Omniva shipping method, you need in Omniva settings page ("Woocommerce" > "Settings" > "Shipping" > "Omniva shipping") on pirces for country settings check "Free with counpon" checkbox and from dropdown select coupon.
![image](https://user-images.githubusercontent.com/71830881/191775011-fd7e11b9-fd3d-4963-8861-795e5f1ade80.png)
