### ISSUE TITLE
WordPress multisite compatibility

### ISSUE THREAD

**Issue by eimkasp** [mijora/omniva-woocommerce#127]
Plugin doesn't work in WordPress multisite setup, when WooCommerce is enabled Network Wide. 

It happens because in `OmnivaLT_Core` class `init()` function `load_launch_hooks()` doesn't get triggered. 

https://github.com/mijora/omniva-woocommerce/blob/35e77f5862568a35d0e73071f28377e42d8a4f2f/omniva-woocommerce/core/class-core.php#L13

I think the issue is that `get_option('active_plugins')` returns the list of plugins activated on single site specifically and does not include plugins that are activated network wide. 

**Quick fix:** 
In `omniva-woocommerce/omniva-woocommerce/core/class-core.php` updating `init()` function to the following:

```
public static function init()
  {
    self::load_classes();
    self::load_init_hooks();
    OmnivaLt_Cronjob::init();

    // Move this outside the condition, because plugin detection doesn't work correctly
    self::load_launch_hooks();
    if ( in_array('woocommerce/woocommerce.php', apply_filters('active_plugins', get_option('active_plugins'))) ) {
      // Remove this just in case of conflict
      // self::load_launch_hooks();
    }
  }
``` 

It would be great if this could be refactored for anyone wanting to use this plugin in a multisite environment. It took me quite a few hours to figure out the issue, but if anyone is looking for the same question, might be useful too.

**Comment by eimkasp** [comment]
I've updated a quick fix to replace initial condition with  `is_plugin_active( 'woocommerce/woocommerce.php')`

```
// This function returns status about WooCommerce activation correctly. 
if ( is_plugin_active( 'woocommerce/woocommerce.php') ) {
      self::load_launch_hooks();
}
```

**Comment by eimkasp** [comment]
I've opened a Pull request to solve this issue:

https://github.com/mijora/omniva-woocommerce/pull/128

**Comment by markakk** [comment]
Hello,

Your PR will be confirmed, but it will not work because the `is_plugin_active` function is not loaded yet.
We improved your change and added it to the plugin in PR #139.
