### ISSUE TITLE
PHP 8.0  compatibility

### ISSUE THREAD

**Issue by Kfishers** [mijora/omniva-woocommerce#129]
Hello!
There is an issue with the checkout page if the only item in the cart is with a disabled shipping ($_POST['shipping_method'] === null).
 Checking if shipping_method is set before the function on the line mentioned in the error solved this. Can I kindly ask you to add this in a future update?

In PHP 7.4 this is a warning but in PHP 8.0 it's a fatal error.

[04-Nov-2022 01:05:45 UTC] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /var/www/******/wp-content/plugins/omniva-woocommerce/omniva-woocommerce.php:2250
Stack trace:
#0 /var/www/******/wp-content/plugins/omniva-woocommerce/omniva-woocommerce.php(2250): in_array()
#1 /var/www/******/wp-includes/class-wp-hook.php(308): omnivalt_terminal_validate()
#2 /var/www/******/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /var/www/******/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /var/www/******/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1163): do_action()
#5 /var/www/******/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(478): WC_Checkout->process_checkout()
#6 /var/www/******/wp-includes/class-wp-hook.php(308): WC_AJAX::checkout()
#7 /var/www/******/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#8 /var/www/******/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /var/www/******/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(93): do_action()
#10 /var/www/******/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax()
#11 /var/www/******/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#12 /var/www/******/wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /var/www/******/wp-includes/template-loader.php(13): do_action()
#14 /var/www/******/wp-blog-header.php(19): require_once('...')
#15 /var/www/******/fix.php(48): require('...')
#16 /var/www/******/index.php(8): include('...')
#17 {main}
  thrown in /var/www/******/wp-content/plugins/omniva-woocommerce/omniva-woocommerce.php on line 2250

**Comment by markakk** [comment]
Hello,

The plugin update we are currently working on (PR: #134) does not seem to have this issue.
