### ISSUE TITLE
Support for company name in the address

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#132]
In case the order has not the firstname or the surname filled in (no customer registration) but has the company name filled in ("get_shipping_company()", "get_billing_company()"), Omniva plugin does not recognise it and returns "Error: ITEMNR1 - CE380709008EE - deliveryAddressee personName missing" when trying to generate the labels.

**Comment by markakk** [comment]
Hello,

Thank you for your suggestion. We added this change in PR #134

**Comment by JanisE** [comment]
Thank you for the change!

Still, there are at least three more places where the company name is not considered:

* https://github.com/mijora/omniva-woocommerce/blob/db378a4b30dfac93957263ba073b0cfa64c70473/omniva-woocommerce/manifest_page.php#L169
* https://github.com/mijora/omniva-woocommerce/blob/db378a4b30dfac93957263ba073b0cfa64c70473/omniva-woocommerce/templates/emails/customer-created_label.php#L28
* https://github.com/mijora/omniva-woocommerce/blob/db378a4b30dfac93957263ba073b0cfa64c70473/omniva-woocommerce/core/class-manifest.php#L70

**Comment by markakk** [comment]
Hello,

We will fix this.

**Comment by markakk** [comment]
The fixes you mentioned were made in PR #142
