### ISSUE TITLE
Omniva plugin settings not being removed from the [prefix]_options table when removing the plugin.

### ISSUE THREAD

**Issue by Elvinas** [mijora/omniva-woocommerce#16]
I'm not sure if this is intended or not, but I noticed that 'woocommerce_omnivalt_settings' option at wc_options table still exists after removing the plugin.

**Comment by LithMage** [comment]
Hi, this is intended as sometimes people uninstall plugin before writing new version. As there is not much of information saved we opted to leave it even if plugin is deleted.
