### ISSUE TITLE
support for Woocommerce Core update

### ISSUE THREAD

**Issue by karaliunas** [mijora/omniva-woocommerce#160]
As you probably know, woocommerce is releasing a [core update, which updates woocommerce DB structure](https://developer.woocommerce.com/2023/03/07/high-performance-order-storage-is-soon-to-be-the-new-normal/)
We are very curious to try this out, but this plugin and one more does not support this major update yet. Just wanted to ask if you guys are planning to support this one and if so - when can we expect an update? Thanks!

**Comment by markakk** [comment]
Hello,

We haven't done anything with this change yet. Maybe we'll build compatibility in the next updates.

**Comment by markakk** [comment]
The task is quite large and there are not many Omniva clients who have a problem with it, so Omniva not planning to do this task now.

**Comment by karaliunas** [comment]
I hear you it's quite a large task, but as Woocommerce states in the mentioned blog post that: "Any extensions that are not marked compatible will no longer be able to be activated on new stores, starting in August." So it means we will have  freeze with current  woocommerce plugin version because omniva plugin will not work if we upgrade. That is sad news..

**Comment by markakk** [comment]
Yes, we saw that. We have informed our managers about this, who will decide what to do and talk to Omniva about it. But it's guaranteed to take time. For now, the task is closed from our side and will be reopened once a decision is made with Omniva.
