### ISSUE TITLE
Support for a (declined) cookie consent

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#181]
Please, implement support for cookie consent, so we can make its use GDPR-compliant.

It seems that this Omniva plugin uses two cookies – `omnivaglobals.cookie_checked_list` and `"omniva_terminal"`.

The first one may be strictly necessary, but if I understand correctly, it's used only for the admin users, so it's not important anyway.

But `"omniva_terminal"` seems like a cookie of the functional cookies category, and as such users need to be able to deny it.
Currently, by looking at the code, that cookie seems to be set no matter what.

**Comment by markakk** [comment]
Hello,

For this problem, please write to your Omniva manager (or department) so that Omniva creates such a task for us.

**Comment by JanisE** [comment]
OK, thank you for a reply! The Omniva manager only offered to sell us individual coding support, even though this is an issue for every (European) company using your plugin (if they want to conform with GDPR). So, I guess, no GDPR support is to be expected by this plugin.
