### ISSUE TITLE
Add hook after success label generation.

### ISSUE THREAD

**Issue by xpresas** [mijora/omniva-woocommerce#182]
Hi.
Please add a hook after label generation

Some users wants to change order status after label generation. Would be a one line implementation on your end and would help us with easy integration of various actions after successful label generations. (Custom emails, custom actions, jobs and etc.)

**Comment by markakk** [comment]
Hello,

For this problem, please write to your Omniva manager (or department) so that Omniva creates such a task for us.

**Comment by markakk** [comment]
Hooks created in PR #200
