### ISSUE TITLE
Fatal error: undefined function get_current_screen() in class-wc.php:21

### ISSUE THREAD

**Issue by EnterTM** [mijora/omniva-woocommerce#183]
After upgrading the version, I encountered the following problem, hpos is not enabled.

PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in /wp-content/plugins/omniva-woocommerce/core/class-wc.php:21
Stack trace:
#0 /wp-content/plugins/omniva-woocommerce/core/class-order.php(391): OmnivaLt_Wc::get_current_screen_id()
#1 /wp-content/plugins/omniva-woocommerce/core/class-order.php(659): OmnivaLt_Order::is_admin_order_edit_page({ORDER_ID_HERE})
#2 /wp-includes/class-wp-hook.php(312): OmnivaLt_Order::admin_order_save_hpos({ORDER_ID_HERE})
#3 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#4 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wp-content/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php(196): do_action('woocommerce_upd...', {ORDER_ID_HERE}, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#6 /wp-content/plugins/woocommerc in /wp-content/plugins/omniva-woocommerce/core/class-wc.php on line 21

System information:
omniva-woocommerce: v1.14.2
WordPress version: 6.3.2
PHP version: 7.4.33
WooCommerce version: 8.1.1
WooCommerce database version: 8.1.1

**Comment by markakk** [comment]
Problem fixed in PR #187
