### ISSUE TITLE
Fatal error when generating a new tracking code

### ISSUE THREAD

**Issue by Evaldash** [mijora/omniva-woocommerce#203]
Hi, after I updated to the newest version, I get a fatal error whenever I generate, or regenerate a new tracking code:

Warning: Undefined array key "pickup_comment" in /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/core/class-api-core.php on line 211

Fatal error: Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file in /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/vendor/setasign/fpdf/fpdf.php:267 Stack trace: #0 /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/vendor/setasign/fpdf/fpdf.php(1058): FPDF->Error() #1 /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/vendor/setasign/fpdf/fpdf.php(1017): FPDF->_checkoutput() #2 /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/vendor/mijora/omniva-api/src/Shipment/Label.php(90): FPDF->Output() #3 /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/core/class-api-core.php(87): Mijora\Omniva\Shipment\Label->downloadLabels() #4 /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/core/class-api.php(42): OmnivaLt_Api_Core->download_labels() #5 /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/core/class-labels.php(65): OmnivaLt_Api->download_shipment_labels() #6 /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/core/class-order.php(331): OmnivaLt_Labels->print_labels() #7 /home/<server>/domains/<site>/public_html/wp-includes/class-wp-hook.php(324): OmnivaLt_Order::post_label_actions() #8 /home/<server>/domains/<site>/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #9 /home/<server>/domains/<site>/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #10 /home/<server>/domains/<site>/public_html/wp-admin/admin-post.php(85): do_action() #11 {main} thrown in /home/<server>/domains/<site>/public_html/wp-content/plugins/omniva-woocommerce/vendor/setasign/fpdf/fpdf.php on line 267

I am able to go back, and the code is generated. I downgraded to version 1.15.0, and the error dissapears.

**Comment by markakk** [comment]
Hello,

Thank you for reporting the issue. Fix added in PR #208.
