### ISSUE TITLE
Courier service zone prices

### ISSUE THREAD

**Issue by RaudseppSiim** [mijora/omniva-woocommerce#213]
Hello,
According to omnivas pricelist, courier shipping has different cost per shipping zones. How can I set up my shipping options so it would not be fixed price? Currently I can only set up Courier shipping per weight.

**Comment by markakk** [comment]
Hello,

Contact Omniva about the problem. If Omniva is unable to answer you and forwards your question to us, then we can get more information for answer to your question.
