### ISSUE TITLE
How to trigger email with tracking info number just after printing shipment labels?

### ISSUE THREAD

**Issue by Elvinas** [mijora/omniva-woocommerce#22]
So here I'm trying to customize this plugin for my own needs. The problem is that the first time shipment label is created my code only sends the email with the invoice but no tracking number is added here even though it's already created. But second and all next consecutive times it works flawlessly.

Here's my code:
  ```
$mailer = WC()->mailer();
  $email_to_send = 'customer_invoice';
  $mails = $mailer->get_emails();

   do_action('woocommerce_before_resend_order_emails', $wc_order);
    // Ensure gateways are loaded in case they need to insert data into the emails.
    WC()->payment_gateways();
    WC()->shipping();

    if (!empty($mails)) {
      foreach ($mails as $mail) {
        if ($mail->id == $email_to_send) {
          $mail->trigger($order->get_id(), $order);
          $wc_order->add_order_note( sprintf( __('%s nusiųsta siuntos numeris.', 'woocommerce'), $mail->title), false, true);
          }
      }
    }

    do_action('woocommerce_after_resend_order_email', $wc_order, $email_to_send);

```

Do you have any idea where I should put it so it works also at the very first time that shipment label is created from Omniva Manifest Admin page. I tried putting my code inside printLabels() method inside foreach loop where it is looping through order ids, but it only works the second time. I'm unable to debug the issue fast, and since there's no test mode I'm really afraid to create shipment labels in Omniva excessively so really trying to avoid spamming Omniva with requests that are only for testing purposes.

Any tips, suggestions would be really appreciated.

**Comment by LithMage** [comment]
Hi.

Are you trying to do this on the latest version of module (as it allready
attaches tracking link to emails)?

**Comment by Elvinas** [comment]
Oh I am, but if I understand it correctly tracking link to emails only works if you send invoice email separately, right? I need to make it work when I click on Print shipment label at Omniva Manifest Admin Page. Here you can take a quick look at the code:

https://github.com/Elvinas/omniva-woocommerce/blob/master/omniva-woocommerce/omniva-woocommerce.php

Starting from line 872 - 894. I tried to put that code after omniva shipment label is already created, but outcome is the same. Maybe I overlooked something.

**Comment by Elvinas** [comment]
Your plugin does everything perfectly what I need, but I'm just trying to trigger that email myself I mean automatically when "Spausdinti lipdukus" button is clicked, so in order to avoid sending those emails separately in orders page.

**Comment by LithMage** [comment]
Hi, looking at your code any sending should be done before line 929. As at
that point tracking number is generated and no errors comes from omniva
api. Both idOrder and track_number are available for you

**Comment by Elvinas** [comment]
Thank you so much for your fast response. Really appreciate it.

So I actually moved my code to the line before 929, and if I recall it correctly I have already tried it, so now just like I told you. First time I only get the email with omniva pickup point address: https://i.ibb.co/6R1RYdN/first.png (without tracking number)

And after clicking 'Spausdinti lipdukus' second time it works as expected: https://i.ibb.co/k81xsCy/second.png
It seems that all the code is already below the code which takes care of creating shipment label and everything but still doesn't work as expected which I find really odd and can't seem to debug it properly. 
https://i.ibb.co/fH7xRrh/fragment.png


I know this is not the place to ask or talk about such things, but if there's some more custom work maybe we can discuss it separately? I would gladly pay you if you could take more deeper look into the problem.

**Comment by LithMage** [comment]
Hi,

You can write us an email at omniva@mijora.lt link this issue for context.

**Comment by markakk** [comment]
This function added in v1.6.0
