### ISSUE TITLE
Untranslated strings (Latvian)

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#224]
Some untranslated labels (for the Latvian language, at least) have appeared in the recent updates.

* Select in map (Parādīt kartē)
* Use my location (Rādīt manā atrašanās vietā)
* Parcel terminals list (Pakomātu saraksts)
* [Omniva] parcel terminals ([Omniva] pakomāti)

![attels](https://github.com/mijora/omniva-woocommerce/assets/1469104/f76c28f6-0507-4e72-bcb6-517dc35f1b43)

![attels](https://github.com/mijora/omniva-woocommerce/assets/1469104/716fc3c1-41f9-46e2-95e4-202d82715116)

How can we ever update your plugin if new untranslated strings are coming in all the time. Please, coordinate the plugin updates with your translation team!

**Comment by markakk** [comment]
Hello,

We would like to inform you that if you have problems or need help with Omniva modules, you must contact Omniva.

We can only briefly answer that we are a Lithuanian company, so we add translations into Lithuanian immediately. We do not have an employee who knows Latvian or Estonian languages, so texts are translated into this languages only when Omniva receives such a request from clients. In this case, we give the texts to Omniva and they sends us the translations after some time.

**Comment by JanisE** [comment]
I see, thank you for the answer!
