### ISSUE TITLE
JS errors if the Omniva plugin doesn't know the address

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#225]
Upon viewing the cart (both registered an non-registered users):
* Uncaught TypeError: document.getElementById(...) is null https://github.com/mijora/omniva-woocommerce/blob/master/omniva-woocommerce/assets/js/omniva.js#L113

Upon opening the check-out (the Omniva option still left untouched by the user; only for non-registered users):
* Uncaught TypeError: this.TMJS.map is null [terminal-mapping.js:641:31]
* Uncaught TypeError: this is undefined [terminal-mapping.js:894:11]

**Comment by JanisE** [comment]
I see that you've addressed this in the code, and I do not see these particular errors anymore. So, let's consider this fixed, thank you!

I encountered a new error though – "Uncaught ReferenceError: omnivaTerminals is not defined" – upon opening the cart, selecting the Omniva delivery method and then opening the cart again. I suppose, this error happens rarely. I'm not going to write to Omniva about it, I'm just letting you know – maybe you want to take a look at fix it.

**Comment by markakk** [comment]
Problem fixed in PR #231

**Comment by markakk** [comment]
Please contact Omniva for the "omnivaTerminals is not defined" error.
