### ISSUE TITLE
Untranslatable string ("Select")

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#227]
The label for the button to select a particular terminal is not translatable. It is missing also from the Lithuanian language file.

![attels](https://github.com/mijora/omniva-woocommerce/assets/1469104/ac763d57-7934-4f64-ba41-d7cd171278db)

**Comment by markakk** [comment]
Hello,

Please contact Omniva regarding this issue so that they can prepare a task for us so and then we can fix it.

**Comment by JanisE** [comment]
All right, I'll contact Omniva. But I wouldn't get my hopes up too high as the last time I tried that, they just offered me paid programming services to fix issues individually in our shop.

**Comment by JanisE** [comment]
Oh, I see that you've already fixed this problem with https://github.com/mijora/omniva-woocommerce/commit/a3c48f275a74250d6bc36fc87e3c5635b2a6e079 Thanks!
