### ISSUE TITLE
Incorrect XML data provided in contact section: person_name is required.

### ISSUE THREAD

**Issue by Esalka** [mijora/omniva-woocommerce#234]
Hello!
We are using plugin Version 1.15.6 and WooCommerce Version 7.8.2.

When clicking the Generate button, an error occurs:
4275 - Incorrect XML data provided in contact section: person_name is required.
Response is in the wrong format

How can this be fixed?

**Comment by markakk** [comment]
Hello,

Please contact Omniva regarding the problem. We will be able to check and fix the problem only after we receive the task from Omniva.
