### ISSUE TITLE
Update "omnivalt.pot" (the base template for translations)

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#236]
Keep the "omnivalt.pot" file up-to-date please.

Currently, it lacks new messages like "Select", "Invalid %s format", "phone number", "The value of this field is used only if the mobile number is not entered.", "On the checkout page, check if the entered mobile phone number format is correct.".

If we synchronise our translation file with the POT template, we cannot translate these strings.

**Comment by markakk** [comment]
Hello,

We try to keep the pot file up-to-date, but due to a lot of work, we just forget about the translations, so the pot file remains out of date. Sorry about that.
