### ISSUE TITLE
Check phone number only if Omniva delivery method is selected

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#241]
Thank you for the phone number check upon checking out – this way the customer can fix it ASAP, and the shop administrator does not have to deal with it when they try printing the Omniva labels.

However, that check should not be applied if another delivery method is selected. We have delivery methods that allow both stationary phone numbers and even foreign phone numbers. Currently, Omniva plugin would still intervene and stop customer from making the order with such phone number.

**Comment by markakk** [comment]
Hello,

Please contact Omniva regarding the problem.

**Comment by JanisE** [comment]
I contacted them about it on the 18th of April and they said they've already reported it to you. I'll remind then, maybe there was some kind of misunderstanding.

**Comment by markakk** [comment]
Hello,

We cant find among the Omniva tasks, a task related to phone number validation.

**Comment by markakk** [comment]
Hello,

We fixed this problem in PR #251. Today we will release a new version of the plugin with this change.
