### ISSUE TITLE
TCPDF throws warning

### ISSUE THREAD

**Issue by Kestutis** [mijora/omniva-woocommerce#4]
I'm getting this error when trying to generate manifest:  
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in \wp-content\plugins\omniva-woocommerce\tcpdf\tcpdf.php on line 17778

Solution would be to update tcpdf to the latest version, because they fixed many php 7.3 version issues:

6.2.19
	- Merge various fixes for PHP 7.3 compatibility and security.

**Comment by LithMage** [comment]
Hi this issue should be fixed with this pull request #5
