### ISSUE TITLE
Add a delivery price rule based on the order amount

### ISSUE THREAD

**Issue by leyakoreya** [mijora/omniva-woocommerce#42]
Hello. I use your plugin and is very user-friendly. But the ability to set the delivery price based on the order amount is sorely lacking.

You have two basic pricing settings for parcel machines and these are: Regular shipping price and free shipping on the order amount.

You can add an additional option (delivery price rule) to also set the delivery amount from the basket amount?

For example.

Order amount from 1-15 euros, delivery cost 3 euros
Order amount 15-40 euros, delivery cost 1 euros
Order amount from 40 euros free shipping.

I will very much wait for your answer.

**Comment by markakk** [comment]
This feature is already available in the latest versions of the plugin.
