### ISSUE TITLE
error for a virtual product (no shipping) at checkout

### ISSUE THREAD

**Issue by edmundspriede** [mijora/omniva-woocommerce#43]
2021-06-05 10:13:13.803447 [NOTICE] [8339] [185.243.215.148:43418#Example] [STDERR] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /usr/local/lsws/Example/html/wp-content/plugins/omniva-woocommerce/omniva-woocommerce.php:2250
Stack trace:
#0 /usr/local/lsws/Example/html/wp-content/plugins/omniva-woocommerce/omniva-woocommerce.php(2250): in_array()
#1 /usr/local/lsws/Example/html/wp-includes/class-wp-hook.php(292): omnivalt_terminal_validate()
#2 /usr/local/lsws/Example/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#3 /usr/local/lsws/Example/html/wp-includes/plugin.php(484): WP_Hook->do_action()
#4 /usr/local/lsws/Example/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1143): do_action()
#5 /usr/local/lsws/Example/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(466): WC_Checkout->process_checkout()
#6 /usr/local/lsws/Example/html/wp-includes/class-wp-hook.php(292): WC_AJAX::checkout()
#7 /usr/local/lsws/Example/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#8 /usr/local/lsws/Example/html/wp-includes/plugin.php(484): WP_Hook->do_action()
#9 /usr/local/lsws/Example/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action()
#10 /usr/local/lsws/Example/html/wp-includes/class-wp-hook.php(292): WC_AJAX::do_wc_ajax()
#11 /usr/local/lsws/Example/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#12 /usr/local/lsws/Example/html/wp-includes/plugin.php(484): WP_Hook->do_action()
#13 /usr/local/lsws/Example/html/wp-includes/template-loader.php(13): do_action()
#14 /usr/local/lsws/Example/html/wp-blog-header.php(19): require_once('...')
#15 /usr/local/lsws/Example/html/index.php(17): require('...')
#16 {main}
  thrown in /usr/local/lsws/Example/html/wp-content/plugins/omniva-woocommerce/omniva-woocommerce.php on line 2250

**Comment by markakk** [comment]
Hello,
Thanks for your report. We will check and fix it in next update.
