### ISSUE TITLE
Disable tracking code adding to email

### ISSUE THREAD

**Issue by Evaldash** [mijora/omniva-woocommerce#57]
Hi, I've encountered an issue. I'm using a seperate plugin for adding the tracking code to customer's emails (I'm using multiple shipping providers), and don't want this plugin to add additional tracking information to the email too. Perhaps such a setting could be implemented within the plugin settings?

**Comment by markakk** [comment]
This option is added with PR #60. Also will be in next update release.

**Comment by Evaldash** [comment]
Thank you! :)
