### ISSUE TITLE
PHP Warnings

### ISSUE THREAD

**Issue by gino0631** [mijora/omniva-woocommerce#58]
With the version 1.9.0 we are getting the following warnings in the logs:

> PHP Warning:  Undefined array key "api_country" in /var/www/html/wp-content/plugins/omniva-woocommerce/includes/class-shipping-method.php on line 52
> PHP Warning:  Undefined array key "method_po" in /var/www/html/wp-content/plugins/omniva-woocommerce/includes/class-shipping-method.php on line 1061

What could be the reason for that?

**Comment by markakk** [comment]
Reason is new settings in version 1.9.0.
This warnings fixed in Pull Request #59. Fixes will be added in next plugin update.
