### ISSUE TITLE
"Disable for specific categories" does not show any categories

### ISSUE THREAD

**Issue by mihkelmuhkel** [mijora/omniva-woocommerce#69]
"Disable for specific categories" does not discover any categories that are set up on my page.
Shows "No results" already when no keyword is entered.
Same when searching for excisting category

![image](https://user-images.githubusercontent.com/76699118/152634893-b47788de-a61f-4cc0-8e49-a8f799a27877.png)

**Comment by markakk** [comment]
Hello,

To check this problem, we need your website admin and FTP logins. Please write to us (problem and logins) to our email omniva@mijora.lt
