### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by Evaldash** [mijora/omniva-woocommerce#70]
I was browsing through the plugin files and noticed that the generated PDF names in the omniva-woocommerce/pdf folder are incremented. That's not good! If someone manages to stumble on one in a site, say  http:.//site.com/wp-content/plugins/omniva-woocommerce/pdf/1020.pdf, they could easily go through the others by incrementing and view the customer data (Names and phone numbers), that could be a GDPR violation. I'd suggest using random strings for the PDF names instead.

**Comment by markakk** [comment]
Thank you for your observation. We will try to figure out how improve that in next plugin update.
