### ISSUE TITLE
Selecting Omniva parcel terminal on the map

### ISSUE THREAD

**Issue by JanisE** [mijora/omniva-woocommerce#75]
The map interface for selecting Omniva terminal is not working properly.

See the video: https://youtu.be/ZtEeDOItQKI

* The active terminal marker is jumping around the map when navigating.
* The markers are switching the positions when clicked upon.

Plug-in version: 1.9.2.1

**Comment by markakk** [comment]
Looks like CSS animation conflict. Created PR #76 with this bug fix.
Changes will be added in next plugin update.
