### ISSUE TITLE
Conflict with DPD plugin

### ISSUE THREAD

**Issue by rudolfgusta** [mijora/omniva-woocommerce#81]
After updating to the newest version Omniva plugin causes the DPD parcel station dropdown to be shown several times (4 to 7 times for the customer).

![275031124_441837274290628_3838207518480474315_n](https://user-images.githubusercontent.com/69973867/156240189-14b65596-646b-4d2a-b46d-a2444726e845.png)

**Comment by iniduoh** [comment]
After this last update I also got the exact same problem but with LPExpress shipping plugin/option.

**Comment by markakk** [comment]
Hello,

This problem fixed in PR #80. Plugin update with this fix we still preparing.
