### ISSUE TITLE
Printing not working in admin panel after update [1.10.1]

### ISSUE THREAD

**Issue by leyakoreya** [mijora/omniva-woocommerce#88]
Hello

After updating to the latest version, I had problems printing stickers and had to go back to the previous version

**Comment by markakk** [comment]
Hello,

Maybe you can write your problem to our email omniva@mijora.lt? We need check this problem in your website.

**Comment by leyakoreya** [comment]
The ability to validate a phone number is very lacking, as customers often order, for example, from Estonia or Lithuania, but indicate Finnish or other country numbers. And therefore it is impossible to print the sticker if the number is not indicated for the country where the shipment is going

  
>Понедельник, 28 марта 2022, 14:19 +03:00 от Marijus Kundelis ***@***.***>:
> 
> 
>Hello,
>Maybe you can write your problem to our email  ***@***.*** ? We need check this problem in your website.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <mijora/omniva-woocommerce/issues/88/1080524431 @ github . com> 
 
 
 
Best Regards
LeyaKo OÜ
Estonia, Tallinn
+37254615591
www.leyakoreya.ee  
  Facebook
Instagram
  TikTok   @leyakoreya

We are glad to cooperate
