### ISSUE TITLE
Critical error when enabled php 8.1

### ISSUE THREAD

**Issue by kutmaster** [mijora/omniva-woocommerce#89]
Klaidos tipas: E_ERROR, rasta eilutėje 243, faile /var/www/clients/client34/web86/web/wp-content/plugins/omniva-woocommerce/includes/class-core.php. Klaidos pranešimas: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/clients/client34/web86/web/wp-content/plugins/omniva-woocommerce/includes/class-core.php:243
Stack trace:
#0 /var/www/clients/client34/web86/web/wp-includes/class-wp-hook.php(307): OmnivaLt_Core::admin_notices()
#1 /var/www/clients/client34/web86/web/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /var/www/clients/client34/web86/web/wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /var/www/clients/client34/web86/web/wp-admin/admin-header.php(303): do_action()
#4 /var/www/clients/client34/web86/web/wp-admin/admin.php(239): require_once('...')
#5 {main}
  thrown

**Comment by markakk** [comment]
Sveiki,
Ši klaida pasireiškia tik tada, kai yra naudojama PHP versija 8.1?
---
Hello,
This error occurs only when PHP 8.1 version is active?

**Comment by kutmaster** [comment]
Sveiki, 
taip, ši klaida pasirodo kai naudoju php8.1
Išmėginau su php8.0 tai klaidos nemeta

**Comment by markakk** [comment]
Paskaičius apie PHP 8.1, matome, jog tikrai įvyko kažkoks pasikeitimas, kuris gali sukelti Jūsų nurodytą klaidą. Tačiau iš teorinės medžiagos sunku suprasti būtent kokia problema (koks pasikeitimas) atsirado. Reiktu mums išbandyti įskiepį šioje PHP versijoje, tačiau šiuo metu dar negalime to padaryti. Manome, jog PHP 8.1 versiją turėsime tik balandžio pabaigoje, todėl Jūsų nurodytos klaidos pataisymo dar reikės palaukti.

**Comment by mikmanic** [comment]
I had a similar problem when adding a product to cart. Happens with php 8 and 8.1.
````
PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /public/wp-content/plugins/woocommerce/includes/wc-cart-functions.php:476
Stack trace:
#0 /public/wp-content/plugins/woocommerce/includes/wc-cart-functions.php(476): array_keys(NULL)
#1 /public/wp-content/plugins/woocommerce/includes/wc-cart-functions.php(412): wc_shipping_methods_have_changed(0, Array)
#2 /public/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1451): wc_get_chosen_shipping_method_for_package(0, Array)
#3 /public/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1420): WC_Cart->get_chosen_shipping_methods(Array)
#4 /public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(339): WC_Cart->calculate_shipping()
#5 /public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(850): WC_Cart_Totals->get_shipping_from_cart()
#6 /public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(144): WC_Cart_Totals->calculate_shipping_totals()
#7 /public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(134): WC_Cart_Totals->calculate()
#8 /public/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1398): WC_Cart_Totals->__construct(Object(WC_Cart))
#9 /public/wp-includes/class-wp-hook.php(305): WC_Cart->calculate_totals()
#10 /public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#11 /public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#12 /public/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1276): do_action('woocommerce_add...', '3c59dc048e88502...', 21, 1, 0, Array, Array)
#13 /public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(824): WC_Cart->add_to_cart(21, 1)
#14 /public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(796): WC_Form_Handler::add_to_cart_handler_simple(21)
#15 /public/wp-includes/class-wp-hook.php(307): WC_Form_Handler::add_to_cart_action('')
#16 /public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#17 /public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#18 /public/wp-settings.php(620): do_action('wp_loaded')
#19 /wp-config.php(85): require_once('/home/web/...')
#20 /public/wp-load.php(55): require_once('/home/web/...')
#21 /public/wp-blog-header.php(13): require_once('/home/...')
#22 /public/index.php(17): require('/home/web/...')
#23 {main}
  thrown in /public/wp-content/plugins/woocommerce/includes/wc-cart-functions.php on line 476
````

I believe the problem was class-frontend.php method "change_methods_position". On line 22:
````
if ( ! $rates )  return;
````
replaced with:
````
if ( ! $rates )  return $rates;
````
Apparently rates can not be null and should return empty array. The fix worked for me.

**Comment by markakk** [comment]
Hello,

@mikmanic, we think you're right, so we fixed it in PR: #135.

@kutmaster Šiuo metu Wordpress naujausia versija (6.1.1) vis dar turi klaidų PHP 8.1 sistemoje, kurios mums trukdo tinkamai pritaikyti Omniva įskiepį, todėl vis dar laukiame kol būsimų Wordpress atnaujinimų su pataisytomis problemomis. Omniva įskiepis bus pilnai pritaikytas PHP 8.0 sistemai išėjus naujam įskiepio atnaujinimui, kurį ruošiame PR #134.

**Comment by markakk** [comment]
In our testing with PHP 8.1, we were unable to detect the listed problems. If you still have issues with plugin version 1.12.3 or later, please let us know.
